image: node:16

pipelines:
  branches:
    master:
      - step:
          name: Code validation - Lint
          script:
            - npm install
            - npm run lint
          caches:
            - node
      - step:
          name: Code validation - Types
          script:
            - npm install
            - npm run check-types
          caches:
            - node
