name: Code validation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - run: npm run lint
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - run: npm run check-types
